script:
  - "npm test"

notifications:
  irc:
    - "chat.freenode.net#sequelizejs"

language: node_js

node_js:
  - "0.10"

before_script:
  - npm install sequelize@$(echo $SEQUELIZE)

env:
  - SEQUELIZE=^1.0.0
  - SEQUELIZE=^2.0.0
  - SEQUELIZE=^3.0.0
