sudo: required
dist: trusty

language: node_js

node_js:
  - '4'
  - '6'
  - '7'

env:
  - SEQUELIZE=^1.0.0
  - SEQUELIZE=^2.0.0
  - SEQUELIZE=^3.0.0

before_script:
  - npm install sequelize@$(echo $SEQUELIZE)
  - npm run build

script:
  - "npm test"

notifications:
  irc:
    - "chat.freenode.net#sequelizejs"
