script:
  - "npm test"

notifications:
  irc:
    - "chat.freenode.net#sequelizejs"

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
  - "4"
  - "5"

before_script:
  - npm install sequelize@$(echo $SEQUELIZE)

env:
  - SEQUELIZE=^1.0.0 CXX=g++-4.8
  - SEQUELIZE=^2.0.0 CXX=g++-4.8
  - SEQUELIZE=^3.0.0 CXX=g++-4.8

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
